default_stages:
- commit
exclude: docs|node_modules|migrations|.git|.tox|.private
fail_fast: true
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: black
    language_version: python3.8
  repo: https://github.com/psf/black
  rev: 22.6.0
- hooks:
  - id: isort
    language_version: python3.8
  repo: https://github.com/timothycrosley/isort
  rev: 5.11.5
- hooks:
  - additional_dependencies:
    - Django==3.2.14
    - Faker==13.15.1
    - dateparser==1.1.1
    - django-admin-autocomplete-filter==0.7.1
    - django-admin-lightweight-date-hierarchy==1.0.1
    - django-environ==0.9.0
    - furl==2.1.3
    - psycopg2-binary==2.8.6
    - requests==2.28.1
    - retry==0.9.2
    - types-pytz==2022.1.2
    - types-requests==2.28.7
    - types-retry==0.9.9
    - types-dateparser==1.1.4
    - types-Markdown==3.4.0
    - unidecode==1.3.4
    args:
    - --show-error-codes
    id: mypy
    language_version: python3.8
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
- hooks:
  - additional_dependencies:
    - flake8-bugbear==22.7.1
    - flake8-comprehensions==3.10.0
    - flake8-isort==4.1.2
    - flake8-print==5.0.0
    args:
    - --config=setup.cfg
    id: flake8
    language_version: python3.8
  repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
